name: Production CD

on:
  workflow_run:
    workflows: [Test CD]
    types:
      - completed

jobs:
  deploy-prod-repository:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --requirement requirements.txt
        pip install --requirement requirements-test.txt
    - name: Build package
      run: |
        python -m build
    - name: Publish the package with twine
      run: |
        twine upload --repository pypi --username ${{ secrets.PYPI_API_USER }} --password ${{ secrets.PYPI_API_TOKEN }} dist/*
